
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_filament_app
    restart: always
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www
      - /var/www/node_modules
      - /var/www/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - project_network

networks:
  project_network:
    driver: bridge