services:
  app:
    build:
      context: .           # Mengarahkan Docker untuk membaca Dockerfile di atas
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - avablox-net

  db:
    image: mysql:8.0       # Spesifikasi MySQL dideklarasikan langsung di sini
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql # Mengamankan data dari kehilangan saat container mati
    networks:
      - avablox-net

networks:
  avablox-net:
    driver: bridge

volumes:
  db_data: