<?php

namespace App\Filament\Resources\Reviewers\Pages;

use App\Filament\Resources\Reviewers\ReviewerResource;
use App\Models\Reviewer;
use App\Models\User;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class CreateReviewer extends CreateRecord
{
    protected static string $resource = ReviewerResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        return DB::transaction(function () use ($data): Reviewer {
            $plainPassword = $data['password'] ?? null;
            $autoGenerated = false;

            if (empty($plainPassword)) {
                $plainPassword = Str::password(12, true, true, false);
                $autoGenerated = true;
            }

            $user = User::create([
                'email' => $data['email'],
                'password' => Hash::make($plainPassword),
                'role' => 'REVIEWER',
                'status' => 'ACTIVE',
            ]);

            $reviewer = Reviewer::create([
                'user_id' => $user->id,
                'nama_lengkap' => $data['nama_lengkap'],
                'nip' => $data['nip'] ?? null,
            ]);

            Notification::make()
                ->title('Reviewer berhasil dibuat')
                ->body(
                    $autoGenerated
                        ? "Email: {$user->email}\nPassword (auto): {$plainPassword}\n\nSimpan password ini sekarang — tidak akan ditampilkan lagi."
                        : "Email: {$user->email}\nPassword: gunakan yang Anda input."
                )
                ->success()
                ->persistent()
                ->send();

            return $reviewer;
        });
    }
}
