<?php

namespace App\Filament\Resources\Users\Pages;

use App\Filament\Resources\Users\UserResource;
use Filament\Resources\Pages\CreateRecord;

class CreateUser extends CreateRecord
{
    protected static string $resource = UserResource::class;
 
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function handleRecordCreation(array $data): \Illuminate\Database\Eloquent\Model
    {
        return \Illuminate\Support\Facades\DB::transaction(function () use ($data) {
            $plainPassword = $data['password'] ?? null;
            $autoGenerated = false;

            if (empty($plainPassword) && $data['role'] === 'REVIEWER') {
                $plainPassword = \Illuminate\Support\Str::password(12, true, true, false);
                $autoGenerated = true;
                $data['password'] = $plainPassword;
            }

            $user = \App\Models\User::create([
                'email' => $data['email'],
                'password' => $data['password'] ? \Illuminate\Support\Facades\Hash::make($data['password']) : \Illuminate\Support\Facades\Hash::make('password'),
                'role' => $data['role'],
                'status' => $data['status'],
            ]);

            if ($data['role'] === 'REVIEWER') {
                \App\Models\Reviewer::create([
                    'user_id' => $user->id,
                    'nama_lengkap' => $data['nama_lengkap'],
                    'nip' => $data['nip'] ?? null,
                ]);

                \Filament\Notifications\Notification::make()
                    ->title('Reviewer berhasil dibuat')
                    ->body(
                        $autoGenerated
                            ? "Email: {$user->email}\nPassword (auto): {$plainPassword}\n\nSimpan password ini sekarang — tidak akan ditampilkan lagi."
                            : "Email: {$user->email}\nPassword: gunakan yang Anda input."
                    )
                    ->success()
                    ->persistent()
                    ->send();
            } elseif ($data['role'] === 'PESERTA') {
                $domain = strtolower(substr(strrchr($data['email'], '@') ?: '@', 1));
                $institusi = \App\Models\Institusi::create([
                    'nama_institusi' => $data['nama_pt'],
                    'jenis_institusi' => $data['jenis_pt'],
                    'domain_email' => $domain ?: null,
                ]);

                \App\Models\Pengumpulan::create([
                    'user_id' => $user->id,
                    'institution_id' => $institusi->id,
                    'tahun_periode' => date('Y'),
                    'status' => 'ACTIVE',
                    'nama_pic' => $data['nama_pic'],
                    'jabatan_pic' => $data['jabatan_pic'],
                    'no_hp_pic' => $data['no_hp_pic'],
                ]);
            }

            return $user;
        });
    }
}
